
# SEO
title: The Stories of Their Lives.
description: A static site where stories come to life.

# social
social_link: github
social_username: Closer2U
github_repo: invisible_nerds # the GitHub repo name for your project
github_username: Closer2U
theme_color: black

# Theme
#remote_theme: 'internet-de-france/swiss'
baseurl: '/invisible_nerds'

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category_name: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: ""

# Stastic UI
remote_theme_layouts: 
  - ""
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble

theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow


